= Asciidoctor / reveal.js slides example
:icons: font
:source-highlighter: highlightjs
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro

toc::[]

== Overview

The slides corresponding to the document https://github.com/Ardemius/asciidoctor-presentation/blob/master/asciidoctor-revealjs-slides/asciidoctor-revealjs-slides-example.adoc[asciidoctor-revealjs-slides-example.adoc] can be http://ardemius.github.io/asciidoctor-presentation/asciidoctor-revealjs-slides/asciidoctor-revealjs-slides-example.html[*viewed online here*], by using the *GitHub pages* of the project.

=== Handling reveal.js as a git submodule

As https://github.com/hakimel/reveal.js[reveal.js] is defined as a *submodule* in the subfolder `asciidoctor-revealjs-slides`, to *retrieve its content*, you need:

* either to use the `--recursive` option of the `clone` command: +
----
git clone --recursive https://github.com/Ardemius/asciidoctor-presentation
----
* or: +
----
git clone https://github.com/Ardemius/asciidoctor-presentation
git submodule init
git submodule update --recursive
----
* or even: +
----
git clone https://github.com/Ardemius/asciidoctor-presentation
git submodule update --init --recursive
----

[NOTE]
====
For more info on *how to handle Git submodules* (retrieve content, update, delete), see this excellent article from Delicious Insights : +
https://delicious-insights.com/fr/articles/git-submodules/
====

=== Update reveal.js content to a newer version

In case you create your own presentation with a repo containing a reveal.js submodule, you will sometimes need to update the content of the reveal.js folder to a more recent version.

If you are *the one that needs to update the submodule content in the first place*, and then share the changes with others, here are the commands to use : 

[source, bash]
----
# go to submodule folder 
cd <path to reveal.js folder>
# fetch all distant changes
git fetch
# checkout in submodule working directory the content you need (like the branch you need)
git checkout -q <commit-sha1, tag name or branch name>
# then go back to superproject and commit in it your changes to the submodule 
cd <path to your repo main folder>
git commit -am "moved submodule from x.y.z to a.b.c"
----

If you need to *retrieve in an already existing repo a change done to one of its submodule* : 

[source, bash]
----
# first retrieve all changes from the superproject, including the ones targeting .gitmodules file
git pull
# then use "git submodule sync" command to update the configuration of your submodule
git submodule sync --recursive
# and finally, now its configuration is correct, update the content of your submodule itself
git submodule update --init --recursive
----

== Installation of Asciidoctor and its reveal.js backend

Everything is explained in the https://github.com/Ardemius/asciidoctor-presentation#installation-instructions[main doc of the repo]. +
Right now (2021), my preferred way to run Asciidoctor with reveal.js is to use their *Docker image*, as explained https://github.com/Ardemius/asciidoctor-presentation/blob/master/README.adoc#running-a-asciidoctor-docker-container--easiest-solution-[here].

=== Use Asciidoctor Docker container

As mentioned just above, everything is explained in this repo, https://github.com/Ardemius/asciidoctor-presentation/blob/master/README.adoc#running-a-asciidoctor-docker-container--easiest-solution-[here]

=== OLD WAY : No-brainer JRuby / Bundler install

Detailed information about Asciidoctor and reveal.js installation with JRuby and Bundler can be found on http://jruby.org/[*JRuby site*] and on the https://docs.asciidoctor.org/reveal.js-converter/latest/setup/ruby-setup/[Reveal.js converter for Asciidoctor documentation].

Just as a convenience, here is a no-brainer install procedure for *Asciidoctor* / *reveal.js* backend using *JRuby* and *Bundler* :

. Install *JRuby*
.. Download https://s3.amazonaws.com/jruby.org/downloads/1.7.26/jruby-bin-1.7.26.zip[JRuby 1.7.xx as a zip]
.. Uncompress it at some path
.. Add `<install_folder>\jruby-1.7.xx\bin` to your `PATH` environment variable
. Install *Bundler*
.. In a command windows, run:
+
[source,bash]
----
$ gem install bundler
----
. Install of the *Asciidoctor / reveal.js stack*
.. Create a folder for your slides project
.. In that folder, create a file named `Gemfile` with the following content:
+
----
source 'https://rubygems.org'

gem 'asciidoctor-revealjs' # latest released version
#gem 'asciidoctor-revealjs', github: 'asciidoctor/asciidoctor-reveal.js' # github master branch
----	
.. Install the gems into the project
+
[source,bash]
----
$ bundle config --local github.https true
$ bundle --path=.bundle/gems --binstubs=.bundle/.bin
----
.. Copy or clone *reveal.js presentation framework*
+
[source,bash]
----
$ git clone -b 3.3.0 --depth 1 https://github.com/hakimel/reveal.js.git
----
+
[WARNING]
====
If you *already retrieved* the *reveal.js folder* (see the https://github.com/Ardemius/asciidoctor-presentation/tree/master/asciidoctor-revealjs-slides#asciidoctor--revealjs-slides-example[submodule details at the beginning of the document]), *bypass* this step.
====
. That's it! :ok_hand:

== Generation of the slides

Again, the whole process is explained in the https://github.com/Ardemius/asciidoctor-presentation#slides-rendering-with-revealjs[main doc of the repo].

But, as a reminder, here is the command to execute in your Docker running container:

[source,bash]
----
asciidoctor-revealjs </path/to/asciidoctor-document> -D </path/to/output-dir> -o <generated-filename>
----
